#!/usr/bin/env python3
# Copyright 2026 Haniel Vásquez Morales
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Writes the false-belief world.

    make_world.py --out /tmp/false_belief.world

One world serves all three floors: they differ in whether the robots have a
radio and in what the picker makes of a relocation it does not see, and
neither is in the world. The crate starts in t1. It is named `crate` and is
moved, when a robot carries it, through gazebo_ros_state's set_entity_state,
which this world loads. The dock and the drop are marked on the floor and
have no collision.
"""

import argparse
import importlib.util
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import layout as L  # noqa: E402


def _pass_through_world():
    source = os.path.join(os.path.dirname(L.P.__file__), 'make_world.py')
    spec = importlib.util.spec_from_file_location('pass_through_world', source)
    module = importlib.util.module_from_spec(spec)
    # Its own `import layout` has to find the pass-through layout.
    saved = sys.modules.get('layout')
    sys.modules['layout'] = L.P
    try:
        spec.loader.exec_module(module)
    finally:
        if saved is not None:
            sys.modules['layout'] = saved
    return module


W = _pass_through_world()

STATE_PLUGIN = """
    <plugin name="gazebo_ros_state" filename="libgazebo_ros_state.so">
      <ros><namespace>/gazebo</namespace></ros>
      <update_rate>20.0</update_rate>
    </plugin>
"""


def crate():
    """A tote with a darker rim, standing on the floor of its first bay."""
    x, y = L.crate_rest(L.CRATE_START)
    w, d, h = L.CRATE_SIZE
    body = '<ambient>0.50 0.33 0.16 1</ambient><diffuse>0.62 0.42 0.20 1</diffuse>'
    rim = '<ambient>0.22 0.14 0.07 1</ambient><diffuse>0.28 0.18 0.09 1</diffuse>'
    return f"""    <model name="crate">
      <static>true</static>
      <pose>{x:.3f} {y:.3f} {h / 2:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="body">
          <geometry><box><size>{w} {d} {h}</size></box></geometry>
        </collision>
        <visual name="body">
          <geometry><box><size>{w} {d} {h}</size></box></geometry>
          <material>{body}</material>
        </visual>
        <visual name="rim">
          <pose>0 0 {h / 2 - 0.02:.3f} 0 0 0</pose>
          <geometry><box><size>{w + 0.02:.2f} {d + 0.02:.2f} 0.04</size></box></geometry>
          <material>{rim}</material>
        </visual>
      </link>
    </model>
"""


def pad(name, centre, size, rgb):
    """A marking on the floor: seen in the frame, not by the lasers."""
    x, y = centre
    w, d = size
    r, g, b = rgb
    return f"""    <model name="{name}">
      <static>true</static>
      <pose>{x:.3f} {y:.3f} 0.004 0 0 0</pose>
      <link name="link">
        <visual name="pad">
          <geometry><box><size>{w} {d} 0.008</size></box></geometry>
          <material><ambient>{r} {g} {b} 1</ambient><diffuse>{r} {g} {b} 1</diffuse></material>
        </visual>
      </link>
    </model>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--camera', default=','.join(str(v) for v in L.OPENING_SHOT),
                    help='X,Y,Z,PITCH,YAW the Gazebo view opens on')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    header = W.HEADER.replace('<world name="pass_through">', '<world name="false_belief">')
    header = header.replace('Generated by tools/make_world.py. Do not edit: edit tools/layout.py.',
                            'Generated by false_belief_demo/tools/make_world.py.')
    parts = [header, STATE_PLUGIN]

    shelves = L.P.block_shelves() + L.P.storage_shelves()
    parts.append(f'\n    <!-- Racking: {len(L.P.block_shelves())} units in the block, '
                 f'{len(L.P.storage_shelves())} in storage. -->\n')
    for i, (x, y) in enumerate(shelves):
        parts.append(W.include(L.SHELF_MODELS[i % 2], f'shelf_{i:03d}', x, y, L.SHELF_YAW))

    parts.append('\n    <!-- Dispatch and storage clutter. -->\n')
    for i, (model, x, y, yaw) in enumerate(L.CLUTTER):
        parts.append(W.include(model, f'clutter_{i:02d}', x, y, yaw))

    parts.append(f'\n    <!-- The crate, in {L.CRATE_START}. -->\n')
    parts.append(crate())
    parts.append('\n    <!-- The picker\'s dock and the drop, marked on the floor. -->\n')
    parts.append(pad('dock_pad', L.DOCK, L.DOCK_PAD, (0.16, 0.36, 0.70)))
    parts.append(pad('drop_pad', L.DROP, L.DROP_PAD, (0.20, 0.55, 0.30)))

    parts.append(W.camera([float(v) for v in args.camera.split(',')]))
    parts.append(W.FOOTER)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, 'w') as fh:
        fh.write(''.join(parts))
    print(f'{args.out}: {len(shelves)} shelves, the crate in {L.CRATE_START}')


if __name__ == '__main__':
    main()
