#!/usr/bin/env python3
# Copyright 2026 Haniel Vásquez Morales
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Writes the pass-through world for one state of the three bays.

    make_world.py --open t2 --out /tmp/pass_through_t2.world

The three worlds differ by which two bays hold a load and by nothing else, so a
run that comes out differently in two of them came out differently because of
what the robots found. The robots are not in the world: the launch spawns them,
one namespaced copy each.

`--camera X,Y,Z,PITCH,YAW` sets the pose the Gazebo view opens on, which is
what is on screen until the camera is told which robot to follow.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import layout as L  # noqa: E402


HEADER = """<?xml version="1.0" ?>
<!-- Generated by tools/make_world.py. Do not edit: edit tools/layout.py. -->
<sdf version="1.6">
  <world name="pass_through">

    <physics name="default_physics" type="ode">
      <max_step_size>0.002</max_step_size>
      <real_time_factor>1</real_time_factor>
      <real_time_update_rate>500</real_time_update_rate>
    </physics>

    <gravity>0 0 -9.8</gravity>

    <scene>
      <ambient>0.62 0.62 0.62 1</ambient>
      <background>0.75 0.78 0.82 1</background>
      <shadows>false</shadows>
    </scene>

    <light name="sun" type="directional">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 30 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.3 0.2 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>120 120</size></plane></geometry>
          <surface><friction><ode><mu>100</mu><mu2>50</mu2></ode></friction></surface>
        </collision>
      </link>
    </model>

    <include>
      <uri>model://Warehouse</uri>
      <name>hall</name>
      <pose>0 0 0 0 0 0</pose>
      <static>true</static>
    </include>
"""

FOOTER = """
  </world>
</sdf>
"""


def include(uri, name, x, y, yaw):
    return (f'    <include>\n'
            f'      <uri>model://{uri}</uri>\n'
            f'      <name>{name}</name>\n'
            f'      <pose>{x:.3f} {y:.3f} 0 0 0 {yaw:.4f}</pose>\n'
            f'      <static>true</static>\n'
            f'    </include>\n')


def box(name, b, height=3.9, rgb=(0.35, 0.38, 0.42)):
    x0, y0, x1, y1 = b
    cx, cy = 0.5 * (x0 + x1), 0.5 * (y0 + y1)
    sx, sy = x1 - x0, y1 - y0
    colour = f'{rgb[0]} {rgb[1]} {rgb[2]} 1'
    return f"""    <model name="{name}">
      <static>true</static>
      <pose>{cx:.3f} {cy:.3f} {height / 2:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{sx:.3f} {sy:.3f} {height:.3f}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{sx:.3f} {sy:.3f} {height:.3f}</size></box></geometry>
          <material><ambient>{colour}</ambient><diffuse>{colour}</diffuse></material>
        </visual>
      </link>
    </model>
"""


def camera(pose):
    x, y, z, pitch, yaw = pose
    return f"""
    <gui fullscreen="0">
      <camera name="user_camera">
        <pose>{x} {y} {z} 0 {pitch} {yaw}</pose>
        <view_controller>orbit</view_controller>
        <projection_type>perspective</projection_type>
      </camera>
    </gui>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--open', required=True, choices=sorted(L.TUNNEL_BAYS),
                    help='the one bay left open; the other two hold a load')
    ap.add_argument('--camera', default='0,-30,16,0.62,1.5708',
                    help='X,Y,Z,PITCH,YAW the Gazebo view opens on')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    parts = [HEADER]

    shelves = L.block_shelves() + L.storage_shelves()
    parts.append(f'\n    <!-- Racking: {len(L.block_shelves())} units in the block, '
                 f'{len(L.storage_shelves())} in storage. -->\n')
    for i, (x, y) in enumerate(shelves):
        parts.append(include(L.SHELF_MODELS[i % 2], f'shelf_{i:03d}', x, y, L.SHELF_YAW))

    parts.append('\n    <!-- The end frames closing the block against the walls. -->\n')
    for i, b in enumerate(L.end_frames()):
        parts.append(box(f'end_frame_{i}', b))

    parts.append('\n    <!-- Dispatch and storage clutter. -->\n')
    for i, (model, x, y, yaw) in enumerate(L.CLUTTER):
        parts.append(include(model, f'clutter_{i:02d}', x, y, yaw))

    shut = [t for t in sorted(L.TUNNEL_BAYS) if t != args.open]
    parts.append(f'\n    <!-- The loads: {", ".join(shut)} closed, {args.open} open. '
                 'Not in any floor plan. -->\n')
    for t in shut:
        x, y = L.tunnel_centre(t)
        parts.append(include(L.LOAD_MODEL, f'load_{t}', x, y, 0.0))

    parts.append(camera([float(v) for v in args.camera.split(',')]))
    parts.append(FOOTER)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, 'w') as fh:
        fh.write(''.join(parts))
    print(f'{args.out}: {len(shelves)} shelves, {len(L.CLUTTER)} clutter, '
          f'{args.open} open, {" ".join(shut)} loaded')


if __name__ == '__main__':
    main()
