#!/usr/bin/env python3
# Copyright 2026 Haniel Ulises
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Turns laser scans into the observations a multi-site survey branches on.

`scan_perception.py` is the single-site version of this and watches one robot
at one place. The multi-site domain sends two robots to two sites and scans
both, so what has to be watched is a set of pairs: any of these robots
arriving at any of these sites is an observation waiting to be taken.

Nothing here is told what the executor is doing, and that is deliberate. The
node subscribes to `/fleet_states` and to each robot's scan, and publishes when
a robot it is watching settles at a site it is watching. An observation is
generated by a robot arriving somewhere with a sensor, not by an action being
dispatched, and a perception node that had to be told which action was running
would be reporting the plan back to itself.

What that leaves is a question of attribution, and it belongs to the bridge:
one observation topic carries every site's reading, so the bridge has to know
that a reading published before an action began belongs to some earlier action.
It does -- `resolve_outcome` compares the observation's arrival against the
action's start -- and this node stamps nothing itself.

The arrival test is the delicate part, and its value was measured rather than
chosen. At 1.20 m the single-site demo's reading was taken a metre short of the
waypoint, from where the pallet subtends about 1.0 m and falls the wrong side
of the threshold: it reported `e-scan-clean` in both worlds, took the clean
branch in both, and passed every check in both. A green run proved nothing.

    site_perception.py --ros-args \
        -p sites:="['a07:-3.35:2.0','a15:-3.35:15.75']" \
        -p robots:="['r1:/r1/scan','r2:/r2/scan']"
"""

import math

import rclpy
from rclpy.executors import ExternalShutdownException
from rclpy.node import Node
from rclpy.qos import (QoSDurabilityPolicy, QoSProfile, QoSReliabilityPolicy,
                       qos_profile_sensor_data)

from rmf_fleet_msgs.msg import FleetState
from sensor_msgs.msg import LaserScan
from std_msgs.msg import String


class SitePerception(Node):
    def __init__(self):
        super().__init__('site_perception')

        # 'name:x:y', because a ROS parameter is a flat list of scalars and a
        # site is three values. Colons rather than commas so the same string
        # survives a launch file, a shell and a YAML file unquoted.
        self.declare_parameter('sites', ['a07:-3.35:2.0'])
        # 'robot:scan_topic'. Every robot the domain may send to a site needs
        # a laser, and each laser needs its own topic: Gazebo names a ray
        # plugin's node after the plugin, so two robots from one model file
        # give two nodes of one name and the server segfaults. The fleet launch
        # writes a model per robot with the plugin namespaced, which is what
        # makes these topics distinct.
        self.declare_parameter('robots', ['r1:/r1/scan'])
        self.declare_parameter('observation_topic', '/eplansys/observation')
        self.declare_parameter('site_radius', 0.40)
        self.declare_parameter('settle', 3)
        self.declare_parameter('threshold', 0.70)
        self.declare_parameter('present_outcome', 'e-scan-dirty')
        self.declare_parameter('absent_outcome', 'e-scan-clean')

        g = self.get_parameter
        self.radius = g('site_radius').value
        self.settle = int(g('settle').value)
        self.threshold = g('threshold').value
        self.present = g('present_outcome').value
        self.absent = g('absent_outcome').value

        self.sites = {}
        for spec in g('sites').value:
            name, x, y = spec.split(':')
            self.sites[name] = (float(x), float(y))

        self.nearest = {}      # robot -> nearest finite return, metres
        self.inside = {}       # (robot, site) -> consecutive reports inside
        self.distance = {}     # (robot, site) -> metres, for the log line
        self.reported = set()  # (robot, site) already published for this arrival

        self.robots = {}
        for spec in g('robots').value:
            name, topic = spec.split(':', 1)
            self.robots[name] = topic
            self.nearest[name] = math.inf
            self.create_subscription(
                LaserScan, topic,
                (lambda who: lambda msg: self.on_scan(who, msg))(name),
                qos_profile_sensor_data)

        # Latched, and deep enough for one reading per site. The bridge may
        # subscribe after a reading was taken, and an observation nobody could
        # hear is not an observation; at depth 1 a late subscriber would be
        # handed whichever site reported most recently.
        latched = QoSProfile(
            depth=max(len(self.sites), 1),
            reliability=QoSReliabilityPolicy.RELIABLE,
            durability=QoSDurabilityPolicy.TRANSIENT_LOCAL)
        self.pub = self.create_publisher(
            String, g('observation_topic').value, latched)

        self.create_subscription(FleetState, '/fleet_states', self.on_fleet, 10)
        self.create_timer(0.5, self.decide)

        self.get_logger().info(
            f'watching {len(self.robots)} robots at {len(self.sites)} sites; '
            f'arrival within {self.radius} m held for {self.settle} reports; '
            f'threshold {self.threshold} m')
        for name, (x, y) in sorted(self.sites.items()):
            self.get_logger().info(f'  site {name} at ({x:.2f}, {y:.2f})')
        for name, topic in sorted(self.robots.items()):
            self.get_logger().info(f'  robot {name} reads {topic}')

    def on_scan(self, robot, msg):
        good = [r for r in msg.ranges
                if math.isfinite(r) and msg.range_min <= r <= msg.range_max]
        self.nearest[robot] = min(good) if good else math.inf

    def on_fleet(self, msg):
        for r in msg.robots:
            if r.name not in self.robots:
                continue
            for site, (sx, sy) in self.sites.items():
                key = (r.name, site)
                d = math.dist((r.location.x, r.location.y), (sx, sy))
                self.distance[key] = d
                if d <= self.radius:
                    self.inside[key] = self.inside.get(key, 0) + 1
                else:
                    self.inside[key] = 0
                    # Leaving clears the arrival, so a robot sent back to a
                    # site it has already looked at looks again rather than
                    # having its earlier reading stand in.
                    self.reported.discard(key)

    def decide(self):
        for (robot, site), count in list(self.inside.items()):
            if count < self.settle:
                continue
            if (robot, site) in self.reported:
                continue
            nearest = self.nearest.get(robot, math.inf)
            if not math.isfinite(nearest):
                continue

            outcome = self.present if nearest < self.threshold else self.absent
            self.reported.add((robot, site))
            # "<site> <outcome>", because the outcome alone does not say what
            # it is an outcome of. A robot commonly reaches its site during the
            # `goto` that precedes the scan, so by the time the scan is
            # dispatched this reading is already seconds old -- and with two
            # sites in play, the newest reading on the topic is as likely to be
            # the other one's. The bridge matches on the site.
            self.pub.publish(String(data=f'{site} {outcome}'))
            self.get_logger().info(
                f'{robot} at {site} ({self.distance[(robot, site)]:.2f} m from '
                f'it), nearest return {nearest:.2f} m '
                f'({"<" if nearest < self.threshold else ">="} '
                f'{self.threshold:.2f}) -> {outcome}')


def main():
    rclpy.init()
    node = SitePerception()
    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, ExternalShutdownException):
        # The launch takes the whole stack down when the mission ends, and
        # rclpy raises rather than returning. Left uncaught it exits 1 and the
        # launch reports the perception node as having died, which reads as the
        # sensor failing in a run that in fact finished.
        pass
    node.destroy_node()
    rclpy.try_shutdown()


if __name__ == '__main__':
    main()
