#!/usr/bin/env python3
# Copyright 2026 Haniel Ulises
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Writes the Gazebo Classic world for the larger warehouse.

Two model sets are combined, and the reason is that neither is sufficient
alone. `OpenRobotics/Warehouse` is a 30 by 50 metre hall with walls, a roof and
ten pillars, and it is the only warehouse of that size on Fuel whose collision
mesh is the building rather than a ground plane -- `OpenRobotics/Depot`, which
is the one usually reached for, collides with nothing but the floor. What the
hall has not got is shelving: measured at robot height its interior is 1.2%
occupied, and all of that is pillars.

The shelving is AWS RoboMaker's, whose `ShelfD_01` and `ShelfE_01` do carry
collision meshes, so a laser sees them and `rasterize_world.py` can read a floor
plan off them.

    make_world.py --out worlds/warehouse_xl.world

Gazebo Classic, because that is what the fleet launch drives: `gzserver` with
the factory plugin, and `spawn_entity.py` for the robots.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import layout as L  # noqa: E402


HEADER = """<?xml version="1.0" ?>
<!-- Generated by tools/make_world.py. Do not edit: edit tools/layout.py. -->
<sdf version="1.6">
  <world name="warehouse_xl">

    <physics name="default_physics" type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1</real_time_factor>
      <real_time_update_rate>1000</real_time_update_rate>
    </physics>

    <gravity>0 0 -9.8</gravity>

    <scene>
      <ambient>0.6 0.6 0.6 1</ambient>
      <background>0.75 0.78 0.82 1</background>
      <shadows>true</shadows>
    </scene>

    <light name="sun" type="directional">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 30 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.3 0.2 -0.9</direction>
    </light>
"""

# The hall's own floor is part of its mesh, but a ground plane underneath costs
# nothing and keeps a robot from falling through if the mesh is ever missing.
GROUND = """
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>120 120</size></plane></geometry>
          <surface><friction><ode><mu>100</mu><mu2>50</mu2></ode></friction></surface>
        </collision>
      </link>
    </model>
"""

HALL = """
    <!-- The building. Walls, roof and the ten pillars, all of which collide. -->
    <include>
      <uri>model://Warehouse</uri>
      <name>hall</name>
      <pose>0 0 0 0 0 0</pose>
      <static>true</static>
    </include>
"""

FOOTER = """
  </world>
</sdf>
"""


def include(uri, name, x, y, yaw, static=True):
    return (f'    <include>\n'
            f'      <uri>model://{uri}</uri>\n'
            f'      <name>{name}</name>\n'
            f'      <pose>{x:.3f} {y:.3f} 0 0 0 {yaw:.4f}</pose>\n'
            f'      <static>{"true" if static else "false"}</static>\n'
            f'    </include>\n')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', required=True)
    args = parser.parse_args()

    parts = [HEADER, GROUND, HALL]

    # The racks. Alternating D and E along each row only so that the rows do
    # not read as one repeated object; the two are the same size and the same
    # collision, and nothing downstream distinguishes them.
    parts.append('\n    <!-- Shelving: %d units in %d rows. -->\n'
                 % (len(L.shelf_poses()), L.ROW_COUNT))
    for i, (x, y, yaw) in enumerate(L.shelf_poses()):
        model = 'aws_robomaker_warehouse_ShelfD_01' if i % 2 == 0 \
            else 'aws_robomaker_warehouse_ShelfE_01'
        parts.append(include(model, f'shelf_{i:03d}', x, y, yaw))

    # Clutter at the dock ends, so the floor is not uniformly empty where the
    # robots begin and so a recording has something to show. Placed by hand
    # rather than scattered, because anything that lands in the service lane
    # blocks the only route the whole floor depends on.
    parts.append('\n    <!-- Dock clutter, clear of the lane and the pillars. -->\n')
    clutter = [
        ('aws_robomaker_warehouse_ClutteringA_01', 11.5, -12.0, 0.0),
        ('aws_robomaker_warehouse_ClutteringC_01', -11.5, -12.0, 0.0),
        ('aws_robomaker_warehouse_ClutteringC_01', 11.5, 12.0, 1.5708),
        ('aws_robomaker_warehouse_ClutteringA_01', -11.5, 12.0, 1.5708),
        ('aws_robomaker_warehouse_PalletJackB_01', 10.5, -22.0, 0.0),
        ('aws_robomaker_warehouse_PalletJackB_01', -10.5, 22.0, 3.1416),
        ('aws_robomaker_warehouse_Bucket_01', 12.5, 0.0, 0.0),
        ('aws_robomaker_warehouse_TrashCanC_01', -12.5, 0.0, 0.0),
    ]
    for i, (model, x, y, yaw) in enumerate(clutter):
        if not L.inside_hall(x, y) or not L.clear_of_pillars(x, y):
            raise SystemExit(f'clutter {i} at ({x}, {y}) is not on free floor')
        parts.append(include(model, f'clutter_{i:02d}', x, y, yaw))

    parts.append(FOOTER)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, 'w') as out:
        out.write(''.join(parts))

    print(f'{args.out}: {len(L.shelf_poses())} shelves, {len(clutter)} clutter, '
          f'{L.ROW_COUNT} rows, {2 * len(L.aisles())} aisles')


if __name__ == '__main__':
    main()
